# Generated by Django 4.2.6 on 2023-10-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_pedido_costo_total_usd_pedido_iva_clp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio_clp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
